name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t warehouse-web:ci .

      - name: CI Completed
        run: echo "CI completed successfully."
